// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bczlquactmlfwnxphfwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjemxxdWFjdG1sZndueHBoZnduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzI1MDQsImV4cCI6MjA2NzIwODUwNH0.jAYuR1We7dKrxVe1cooB_q0FNY9gI1sHPOXPCgaIBiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});